In [4]:
import torch 
import torch.nn as nn

ReLU Activation Function:

In [5]:
r= nn.ReLU()
input_test= torch.Tensor([-1,-2,3,-5])
output_test= r(input_test)
print(output_test)

tensor([0., 0., 3., 0.])


Sigmoid Activation Function:

In [6]:
# Calling the sigmoid function
sig = nn.Sigmoid()
 
# Defining tensor
input = torch.Tensor([1,-2,3,-5])
 
# Applying sigmoid to the tensor
output = sig(input)
 
print(output)

tensor([0.7311, 0.1192, 0.9526, 0.0067])


Tanh Activation Function:

In [7]:
# Calling the Tanh function
t = nn.Tanh()
 
# Defining tensor
input = torch.Tensor([1,-2,3,-5])
 
# Applying Tanh to the tensor
output = t(input)
print(output)

tensor([ 0.7616, -0.9640,  0.9951, -0.9999])


Softmax Activation Function:

In [8]:
# Calling the Softmax function with
# dimension = 0 as dimension starts
# from 0
sm = nn.Softmax(dim=0) 
 
# Defining tensor
input = torch.Tensor([1,-2,3,-5])
 
# Applying function to the tensor
output = sm(input)
print(output)

tensor([1.1846e-01, 5.8980e-03, 8.7534e-01, 2.9365e-04])
