<h1>Activation Function in Pytorch<h1>

In [1]:
import torch
import torch.nn as nn

Relu

In [2]:
# defining relu
r = nn.ReLU()
 
# Creating a Tensor with an array
input = torch.Tensor([1, -2, 3, -5])
 
# Passing the array to relu function
output = r(input)
 
print(output)

tensor([1., 0., 3., 0.])


Leaky Relu

In [3]:
# defining Lrelu and the parameter 0.2 is passed to control the negative slope ; a=0.2
r = nn.LeakyReLU(0.2)
 
# Creating a Tensor with an array
input = torch.Tensor([1,-2,3,-5])
 
output = r(input)
 
print(output)

tensor([ 1.0000, -0.4000,  3.0000, -1.0000])


Sigmoid Function

In [4]:
# Calling the sigmoid function
sig = nn.Sigmoid()
 
# Defining tensor
input = torch.Tensor([1,-2,3,-5])
 
# Applying sigmoid to the tensor
output = sig(input)
 
print(output)

tensor([0.7311, 0.1192, 0.9526, 0.0067])


Tanh Function

In [5]:
t = nn.Tanh()
 
# Defining tensor
input = torch.Tensor([1,-2,3,-5])
 
# Applying Tanh to the tensor
output = t(input)
print(output)

tensor([ 0.7616, -0.9640,  0.9951, -0.9999])


Softmax Activation Function

In [6]:
sm = nn.Softmax(dim=0) 
 
# Defining tensor
input = torch.Tensor([1,-2,3,-5])
 
# Applying function to the tensor
output = sm(input)
print(output)

tensor([1.1846e-01, 5.8980e-03, 8.7534e-01, 2.9365e-04])
